import type { Metadata } from "next";
import { ChakraProvider } from "@chakra-ui/react";
import { Inter } from "next/font/google";
import "./globals.css";
import system from "@/app/theme";
import Provider from "./provider";

const inter = Inter({
  variable: "--inter",
  subsets: ["latin"],
  weight: ["200", "300", "400"],
});
export const metadata: Metadata = {
  title: "Fync",
  description: "Generated by create next app",
};

export default function App({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.variable} antialiased`}>
        <Provider>{children}</Provider>
      </body>
    </html>
  );
}
